#!/usr/bin/env python3
"""Preview or install narrow todo-capture permissions for Codex and Claude Code.

Only todo_safe.py is approved. It has no custom-path option; direct todo.py,
setup_permissions.py, and arbitrary Python remain approval-gated.
"""
import argparse
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import time

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from _common import (active_agent, agent_home, data_root, ensure_private_dir,
                     SAFE_SUBCOMMANDS)

MARKER = "# Generated by todo-capture setup_permissions.py; review before trusting."
HERE = os.path.dirname(os.path.abspath(__file__))
SAFE_SCRIPT = os.path.join(HERE, "todo_safe.py")
DIRECT_SCRIPT = os.path.join(HERE, "todo.py")


def command_text(parts, shell=None):
    if shell == "powershell" or (os.name == "nt" and shell != "bash"):
        return subprocess.list2cmdline(parts)
    return shlex.join(parts)


def msys_path(path):
    """Translate a native Windows path (C:\\a\\b) to the MSYS/Git-Bash form (/c/a/b).

    Claude Code's Bash tool on Windows runs commands with forward-slash paths, so a
    rule written with a backslash drive path would never match. Return None when the
    input is not a drive-letter path (nothing to translate)."""
    if len(path) >= 2 and path[1] == ":" and path[0].isalpha():
        rest = path[2:].replace("\\", "/")
        if not rest.startswith("/"):
            rest = "/" + rest
        return f"/{path[0].lower()}{rest}"
    return None


def script_forms(shell=None, script=SAFE_SCRIPT):
    """Every safe-dispatcher path spelling a harness may use on this OS."""
    forms = [script]
    if os.name == "nt":
        m = msys_path(script)
        if m:
            if shell == "bash":
                forms = [m]
            elif shell is None:
                forms.append(m)
    return forms


def interpreter_forms(shell=None):
    """Command-token forms resolving to this Python 3 interpreter."""
    forms = []

    def add(*parts):
        value = tuple(parts)
        if value not in forms:
            forms.append(value)

    executable = os.path.abspath(sys.executable)
    add(executable)
    for name in ("python3", "python"):
        found = shutil.which(name)
        if not found:
            continue
        try:
            same = os.path.samefile(found, executable)
        except OSError:
            same = os.path.realpath(found) == os.path.realpath(executable)
        if same:
            add(name)
            add(os.path.abspath(found))
    if os.name == "nt" and shutil.which("py"):
        add("py", "-3")
    if os.name == "nt" and shell == "bash":
        translated = []
        for form in forms:
            first = msys_path(form[0]) or form[0]
            value = (first, *form[1:])
            if value not in translated:
                translated.append(value)
        return translated
    return forms


def starlark(value):
    return json.dumps(value, ensure_ascii=False)


def _claude_command_rules(script, wildcard=" *"):
    rules = set()
    shells = ("bash", "powershell") if os.name == "nt" else ("bash",)
    for shell in shells:
        tool = "PowerShell" if shell == "powershell" else "Bash"
        for form in interpreter_forms(shell):
            for script_form in script_forms(shell, script):
                for subcommand in SAFE_SUBCOMMANDS:
                    prefix = command_text([*form, script_form, subcommand], shell)
                    rules.add(f"{tool}({prefix}{wildcard})")
    return sorted(rules)


def claude_rules():
    """Pin the safe dispatcher and subcommand; only todo data remains variable."""
    return _claude_command_rules(SAFE_SCRIPT)


def legacy_claude_rules():
    """Rules emitted by the pre-dispatcher version at the current install path."""
    return _claude_command_rules(DIRECT_SCRIPT, wildcard=":*")


def codex_rule_text():
    forms = interpreter_forms()
    one_token = sorted({f[0] for f in forms if len(f) == 1})
    two_token = sorted({f for f in forms if len(f) == 2})
    blocks = [MARKER, ""]
    for script in script_forms():
        for sub in SAFE_SUBCOMMANDS:
            patterns = []
            if one_token:
                first = one_token[0] if len(one_token) == 1 else one_token
                patterns.append([first, script, sub])
            patterns.extend([[a, b, script, sub] for a, b in two_token])
            for pattern in patterns:
                head = pattern[0][0] if isinstance(pattern[0], list) else pattern[0]
                example = [head, *pattern[1:]]
                blocks.extend([
                    "prefix_rule(",
                    f"    pattern={starlark(pattern)},",
                    '    decision="allow",',
                '    justification="Fixed-store todo-capture dispatcher; custom paths are not accepted",',
                f"    match=[{starlark(command_text([*example, '--help']))}],",
                f"    not_match=[{starlark(command_text([*example[:-1], sub + '-extra']))}],",
                    ")",
                    "",
                ])
    return "\n".join(blocks).rstrip() + "\n"


def codex_target():
    return os.path.join(agent_home("codex"), "rules", "todo-capture.rules")


def claude_target():
    return os.path.join(agent_home("claude"), "settings.json")


def claude_state_target():
    return os.path.join(agent_home("claude"), ".todo-capture-permission-state.json")


def legacy_claude_state_target():
    return os.path.join(data_root(), ".permission-state-claude.json")


def atomic_write(path, text):
    parent = os.path.dirname(os.path.abspath(path))
    os.makedirs(parent, mode=0o700, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".todo-capture-", dir=parent, text=True)
    try:
        if os.name != "nt":
            os.chmod(tmp, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        # os.replace can transiently fail with Access-denied on Windows when the
        # target is briefly locked (editor/agent/AV). Retry with short backoff.
        last = None
        for attempt in range(8):
            try:
                os.replace(tmp, path)
                break
            except PermissionError as exc:
                last = exc
                time.sleep(0.25 * (attempt + 1))
        else:
            raise last
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def load_json_object(path):
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        value = json.load(fh)
    if not isinstance(value, dict):
        raise ValueError(f"expected a JSON object in {path}")
    return value


def claude_file_pattern(path, suffix="/**"):
    normalized = msys_path(path) if os.name == "nt" else path.replace("\\", "/")
    normalized = normalized or path.replace("\\", "/")
    return "//" + normalized.lstrip("/") + suffix


def validated_previous_state(state, settings_path):
    """Trust ownership records only for exact paths/rules this setup can own."""
    if not state:
        return {}
    if state.get("settings") != settings_path:
        raise ValueError(
            f"permission state targets unexpected settings file: {state.get('settings')}"
        )
    ddir = data_root()
    current_patterns = {
        f"Read({claude_file_pattern(ddir)})",
        f"Edit({claude_file_pattern(ddir, '/*/*.md')})",
        f"Edit({claude_file_pattern(ddir, '/domains.local.tsv')})",
    }
    # Include the exact broad file rules from the previous release so an owned
    # installation can be narrowed. The old POSIX builder emitted three slashes.
    old_forward = ddir.replace("\\", "/")
    legacy_patterns = {
        f"Read(//{old_forward}/**)",
        f"Edit(//{old_forward}/**)",
        f"Write(//{old_forward}/**)",
    }
    candidates = current_patterns | legacy_patterns

    def owned_shell_rule(rule):
        if not isinstance(rule, str) or "\n" in rule:
            return False
        shell = None
        for tool in ("Bash", "PowerShell"):
            if rule.startswith(tool + "(") and rule.endswith(")"):
                shell = "powershell" if tool == "PowerShell" else "bash"
                break
        if shell is None:
            return False
        body = rule[rule.index("(") + 1:-1]
        if body.endswith(":*"):
            body = body[:-2]
        elif body.endswith(" *"):
            body = body[:-2]
        else:
            return False
        parse_modes = (True, False) if shell == "bash" and os.name == "nt" else (
            shell == "bash",
        )
        scripts = set(script_forms(shell, SAFE_SCRIPT)) | set(
            script_forms(shell, DIRECT_SCRIPT)
        )
        # Pre-dispatcher Windows Bash rules also included native drive paths.
        if shell == "bash" and os.name == "nt":
            scripts |= {SAFE_SCRIPT, DIRECT_SCRIPT}
        for posix in parse_modes:
            try:
                tokens = shlex.split(body, posix=posix)
            except ValueError:
                continue
            tokens = [token.strip('"\'') for token in tokens]
            if len(tokens) not in (3, 4) or tokens[-1] not in SAFE_SUBCOMMANDS:
                continue
            if tokens[-2] not in scripts:
                continue
            interpreter = tokens[:-2]
            executable = interpreter[0].replace("\\", "/").rsplit("/", 1)[-1].lower()
            python_name = re.fullmatch(r"python(?:3(?:\.\d+)?)?(?:\.exe)?", executable)
            if ((len(interpreter) == 1 and python_name)
                    or interpreter == ["py", "-3"]
                    or interpreter == ["py.exe", "-3"]):
                return True
        return False

    added_rules = [rule for rule in state.get("added_rules", [])
                   if rule in candidates or owned_shell_rule(rule)]
    return {
        "settings": settings_path,
        "added_rules": added_rules,
        "added_dir": ddir if state.get("added_dir") == ddir else None,
        "write_path": ddir if state.get("write_path") == ddir else None,
    }


def merged_claude_settings(path, previous_state=None):
    settings = load_json_object(path)
    permissions = settings.setdefault("permissions", {})
    if not isinstance(permissions, dict):
        raise ValueError("settings.permissions must be an object")
    allow = permissions.setdefault("allow", [])
    if not isinstance(allow, list):
        raise ValueError("settings.permissions.allow must be an array")

    previous_state = previous_state or {}
    if previous_state.get("settings") == path:
        previously_added = set(previous_state.get("added_rules", []))
        allow[:] = [rule for rule in allow if rule not in previously_added]

    ddir = data_root()
    read_pattern = claude_file_pattern(ddir)
    entry_pattern = claude_file_pattern(ddir, "/*/*.md")
    # Edit covers current Claude file-editing tools. Keep derived/index/archive/
    # vocabulary/lock/permission state outside direct editing; the dispatcher
    # manages them.
    fs_rules = [f"Read({read_pattern})", f"Edit({entry_pattern})"]
    added = []
    for rule in claude_rules() + fs_rules:
        if rule not in allow:
            allow.append(rule)
            added.append(rule)

    extra = permissions.setdefault("additionalDirectories", [])
    added_dir = None
    if isinstance(extra, list) and ddir not in extra:
        extra.append(ddir)
        added_dir = ddir

    previous_owned_dir = (previous_state.get("settings") == path
                          and previous_state.get("added_dir") == ddir)
    if previous_owned_dir:
        added_dir = ddir

    sandbox = settings.setdefault("sandbox", {})
    if not isinstance(sandbox, dict):
        raise ValueError("settings.sandbox must be an object")
    filesystem = sandbox.setdefault("filesystem", {})
    if not isinstance(filesystem, dict):
        raise ValueError("settings.sandbox.filesystem must be an object")
    allow_write = filesystem.setdefault("allowWrite", [])
    if not isinstance(allow_write, list):
        raise ValueError("settings.sandbox.filesystem.allowWrite must be an array")
    write_path = None
    if ddir not in allow_write:
        allow_write.append(ddir)
        write_path = ddir
    elif (previous_state.get("settings") == path
          and previous_state.get("write_path") == ddir):
        write_path = ddir

    state = {"settings": path, "added_rules": added, "added_dir": added_dir,
             "write_path": write_path}
    return settings, state


def selected_agents(value):
    selected = active_agent(value)
    return ("codex", "claude") if selected == "all" else (selected,)


def preview(agents):
    print("todo-capture permission proposal (no changes yet):")
    print(f"  safe dispatcher: {SAFE_SCRIPT}")
    print(f"  direct helper (not approved): {DIRECT_SCRIPT}")
    print(f"  data dir: {data_root()}")
    for agent in agents:
        if agent == "codex":
            print(f"\nCodex rules file: {codex_target()}")
            print(f"  {len(SAFE_SUBCOMMANDS)} fixed-store subcommands; no custom path support")
        else:
            rules = claude_rules()
            print(f"\nClaude settings: {claude_target()}")
            print(f"  {len(rules)} pinned shell prefixes (dispatcher + subcommand):")
            for r in rules:
                print(f"    {r}")
            print(f"  + Read store; Edit active entries; sandbox write: {data_root()}")
    print("\nStill approval-gated: setup_permissions.py, direct todo.py, and every custom --dir path.")


def install_codex(force=False):
    path = codex_target()
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            existing = fh.read()
        if existing and not existing.startswith(MARKER) and not force:
            raise RuntimeError(f"refusing to overwrite unmanaged rules file: {path} (use --force)")
    atomic_write(path, codex_rule_text())
    print(f"installed Codex rules -> {path}")


def install_claude():
    path = claude_target()
    ensure_private_dir(data_root())
    state_path = claude_state_target()
    legacy_state_path = legacy_claude_state_target()
    previous = load_json_object(state_path) if os.path.exists(state_path) else {}
    if not previous and os.path.exists(legacy_state_path):
        previous = load_json_object(legacy_state_path)
    previous = validated_previous_state(previous, path)
    settings, state = merged_claude_settings(path, previous)
    if os.path.exists(state_path):
        if previous.get("settings") == path:
            state["added_dir"] = state["added_dir"] or previous.get("added_dir")
            state["write_path"] = state["write_path"] or previous.get("write_path")
    existed = os.path.exists(path)
    original = None
    if existed:
        with open(path, encoding="utf-8") as handle:
            original = handle.read()
    try:
        atomic_write(path, json.dumps(settings, indent=2, ensure_ascii=False) + "\n")
        atomic_write(state_path, json.dumps(state, indent=2, ensure_ascii=False) + "\n")
    except Exception:
        if existed:
            atomic_write(path, original)
        else:
            try:
                os.unlink(path)
            except OSError:
                pass
        raise
    if legacy_state_path != state_path and os.path.exists(legacy_state_path):
        try:
            os.unlink(legacy_state_path)
        except OSError as exc:
            print(f"warning: could not remove legacy permission state: {exc}", file=sys.stderr)
    print(f"installed Claude rules -> {path}")


def remove_codex():
    path = codex_target()
    if not os.path.exists(path):
        print(f"Codex rules already absent -> {path}")
        return
    with open(path, encoding="utf-8") as fh:
        if not fh.read().startswith(MARKER):
            raise RuntimeError(f"refusing to remove unmanaged rules file: {path}")
    os.unlink(path)
    print(f"removed Codex rules -> {path}")


def remove_claude():
    state_path = claude_state_target()
    if not os.path.exists(state_path) and os.path.exists(legacy_claude_state_target()):
        state_path = legacy_claude_state_target()
    if not os.path.exists(state_path):
        raise RuntimeError(f"cannot safely remove Claude entries without state file: {state_path}")
    state = load_json_object(state_path)
    path = claude_target()
    state = validated_previous_state(state, path)
    settings = load_json_object(path)
    permissions = settings.get("permissions", {})
    if isinstance(permissions, dict):
        added = set(state.get("added_rules", []))
        allow = permissions.get("allow", [])
        if isinstance(allow, list):
            permissions["allow"] = [r for r in allow if r not in added]
        extra = permissions.get("additionalDirectories", [])
        if state.get("added_dir") and isinstance(extra, list):
            permissions["additionalDirectories"] = [d for d in extra if d != state["added_dir"]]
    sandbox = settings.get("sandbox", {})
    filesystem = sandbox.get("filesystem", {}) if isinstance(sandbox, dict) else {}
    allow_write = filesystem.get("allowWrite", []) if isinstance(filesystem, dict) else []
    if state.get("write_path") and isinstance(allow_write, list):
        filesystem["allowWrite"] = [p for p in allow_write if p != state["write_path"]]
    atomic_write(path, json.dumps(settings, indent=2, ensure_ascii=False) + "\n")
    os.unlink(state_path)
    print(f"removed Claude rules -> {path}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--agent", choices=("auto", "codex", "claude", "all"), default="auto")
    action = ap.add_mutually_exclusive_group()
    action.add_argument("--install", action="store_true", help="write the proposed configuration")
    action.add_argument("--remove", action="store_true", help="remove entries previously installed by this script")
    ap.add_argument("--yes", action="store_true", help="confirm install/remove non-interactively")
    ap.add_argument("--force", action="store_true", help="replace an unmanaged todo-capture.rules file")
    args = ap.parse_args()
    if args.yes and not (args.install or args.remove):
        ap.error("--yes requires --install or --remove")
    agents = selected_agents(args.agent)
    if not args.remove:
        preview(agents)
    else:
        print("todo-capture permission removal proposal:")
        for agent in agents:
            print(f"  {agent}: remove only entries recorded by todo-capture setup")
    if not (args.install or args.remove):
        print("\nDry run only. Re-run with --install --yes after reviewing the proposal.")
        return
    if not args.yes:
        if not sys.stdin.isatty():
            raise RuntimeError("interactive confirmation unavailable; re-run with --yes after user approval")
        verb = "Remove" if args.remove else "Install"
        if input(f"\n{verb} this proposal? [y/N] ").strip().lower() not in ("y", "yes"):
            print("cancelled")
            return
    for agent in agents:
        if agent == "codex" and args.remove:
            remove_codex()
        elif agent == "claude" and args.remove:
            remove_claude()
        elif agent == "codex":
            install_codex(args.force)
        else:
            install_claude()
    if "codex" in agents and not args.remove:
        print("Restart Codex so the new rules are loaded.")


if __name__ == "__main__":
    sys.exit(main())
