#!/usr/bin/env python3
"""Preview or install narrow tool-audit permissions for Codex and Claude Code.

The installer approves only exact fixed profiles exposed by audit.py. It never
approves arbitrary Python, direct helper scripts, custom paths, version probes,
or catalog writes.
"""
import argparse
import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True

from _common import active_agent, agent_home, data_root
from audit import PROFILES


MARKER = "# Generated by tool-audit setup_permissions.py; review before trusting."
HERE = os.path.dirname(os.path.abspath(__file__))
AUDIT_SCRIPT = os.path.join(HERE, "audit.py")


def command_text(parts):
    if os.name == "nt":
        return subprocess.list2cmdline(parts)
    return shlex.join(parts)


def interpreter_forms():
    """Return command-token forms that resolve to this Python 3 interpreter."""
    forms = []

    def add(*parts):
        value = tuple(parts)
        if value not in forms:
            forms.append(value)

    executable = os.path.abspath(sys.executable)
    add(executable)
    for name in ("python3", "python"):
        found = shutil.which(name)
        if not found:
            continue
        try:
            same = os.path.samefile(found, executable)
        except OSError:
            same = os.path.realpath(found) == os.path.realpath(executable)
        if same:
            add(name)
            add(os.path.abspath(found))
    if os.name == "nt" and shutil.which("py"):
        add("py", "-3")
    return forms


def starlark(value):
    return json.dumps(value, ensure_ascii=False)


def codex_rule_text():
    forms = interpreter_forms()
    one_token = sorted({f[0] for f in forms if len(f) == 1})
    two_token = sorted({f for f in forms if len(f) == 2})
    blocks = [MARKER, ""]
    for profile in sorted(PROFILES):
        patterns = []
        if one_token:
            first = one_token[0] if len(one_token) == 1 else one_token
            patterns.append([first, AUDIT_SCRIPT, profile])
        patterns.extend([[a, b, AUDIT_SCRIPT, profile] for a, b in two_token])
        for pattern in patterns:
            example_head = pattern[0][0] if isinstance(pattern[0], list) else pattern[0]
            example = [example_head, *pattern[1:]]
            blocks.extend([
                "prefix_rule(",
                f"    pattern={starlark(pattern)},",
                '    decision="allow",',
                '    justification="Fixed-profile tool-audit command; no passthrough paths or commands",',
                f"    match=[{starlark(command_text(example))}],",
                f"    not_match=[{starlark(command_text([*example[:-1], profile + '-extra']))}],",
                ")",
                "",
            ])
    return "\n".join(blocks).rstrip() + "\n"


def claude_rules():
    return sorted({
        f"Bash({command_text([*form, AUDIT_SCRIPT, profile])})"
        for form in interpreter_forms()
        for profile in PROFILES
    })


def codex_target():
    return os.path.join(agent_home("codex"), "rules", "tool-audit.rules")


def claude_target():
    return os.path.join(agent_home("claude"), "settings.json")


def claude_state_target():
    return os.path.join(data_root("claude"), "permission-state.json")


def atomic_write(path, text):
    parent = os.path.dirname(os.path.abspath(path))
    os.makedirs(parent, mode=0o700, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".tool-audit-", dir=parent, text=True)
    try:
        if os.name != "nt":
            os.chmod(tmp, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def load_json_object(path):
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        value = json.load(fh)
    if not isinstance(value, dict):
        raise ValueError(f"expected a JSON object in {path}")
    return value


def merged_claude_settings(path):
    settings = load_json_object(path)
    permissions = settings.setdefault("permissions", {})
    if not isinstance(permissions, dict):
        raise ValueError("settings.permissions must be an object")
    allow = permissions.setdefault("allow", [])
    if not isinstance(allow, list):
        raise ValueError("settings.permissions.allow must be an array")
    added_rules = []
    for rule in claude_rules():
        if rule not in allow:
            allow.append(rule)
            added_rules.append(rule)

    sandbox = settings.setdefault("sandbox", {})
    if not isinstance(sandbox, dict):
        raise ValueError("settings.sandbox must be an object")
    filesystem = sandbox.setdefault("filesystem", {})
    if not isinstance(filesystem, dict):
        raise ValueError("settings.sandbox.filesystem must be an object")
    allow_write = filesystem.setdefault("allowWrite", [])
    if not isinstance(allow_write, list):
        raise ValueError("settings.sandbox.filesystem.allowWrite must be an array")
    path_rule = data_root("claude")
    added_write_path = False
    if path_rule not in allow_write:
        allow_write.append(path_rule)
        added_write_path = True
    state = {"settings": path, "added_rules": added_rules,
             "write_path": path_rule if added_write_path else None}
    return settings, state


def selected_agents(value):
    selected = active_agent(value)
    return ("codex", "claude") if selected == "all" else (selected,)


def preview(agents):
    print("tool-audit permission proposal (no changes yet):")
    for agent in agents:
        if agent == "codex":
            print(f"\nCodex rules: {codex_target()}")
            print(f"  {len(PROFILES)} fixed audit.py profiles; direct helper scripts remain unapproved")
        else:
            print(f"\nClaude settings: {claude_target()}")
            print(f"  {len(claude_rules())} exact Bash commands (no wildcards)")
            print(f"  sandbox write path: {data_root('claude')}")
    print("\nStill approval-gated: setup_permissions.py, inventory_versions.py, "
          "inventory_learn.py, snapshot_custom.py, and direct scripts with custom flags.")


def install_codex(force=False):
    path = codex_target()
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            existing = fh.read()
        if existing and not existing.startswith(MARKER) and not force:
            raise RuntimeError(f"refusing to overwrite unmanaged rules file: {path} (use --force)")
    atomic_write(path, codex_rule_text())
    print(f"installed Codex rules -> {path}")


def install_claude():
    path = claude_target()
    settings, state = merged_claude_settings(path)
    state_path = claude_state_target()
    if os.path.exists(state_path):
        previous = load_json_object(state_path)
        if previous.get("settings") == path:
            state["added_rules"] = sorted(set(previous.get("added_rules", [])) |
                                          set(state["added_rules"]))
            state["write_path"] = state["write_path"] or previous.get("write_path")
    atomic_write(path, json.dumps(settings, indent=2, ensure_ascii=False) + "\n")
    atomic_write(state_path, json.dumps(state, indent=2, ensure_ascii=False) + "\n")
    print(f"installed Claude rules -> {path}")


def remove_codex():
    path = codex_target()
    if not os.path.exists(path):
        print(f"Codex rules already absent -> {path}")
        return
    with open(path, encoding="utf-8") as fh:
        if not fh.read().startswith(MARKER):
            raise RuntimeError(f"refusing to remove unmanaged rules file: {path}")
    os.unlink(path)
    print(f"removed Codex rules -> {path}")


def remove_claude():
    state_path = claude_state_target()
    if not os.path.exists(state_path):
        raise RuntimeError(f"cannot safely remove Claude entries without state file: {state_path}")
    state = load_json_object(state_path)
    path = state.get("settings") or claude_target()
    settings = load_json_object(path)
    permissions = settings.get("permissions", {})
    allow = permissions.get("allow", []) if isinstance(permissions, dict) else []
    if isinstance(allow, list):
        added = set(state.get("added_rules", []))
        permissions["allow"] = [rule for rule in allow if rule not in added]
    sandbox = settings.get("sandbox", {})
    filesystem = sandbox.get("filesystem", {}) if isinstance(sandbox, dict) else {}
    allow_write = filesystem.get("allowWrite", []) if isinstance(filesystem, dict) else []
    write_path = state.get("write_path")
    if write_path and isinstance(allow_write, list):
        filesystem["allowWrite"] = [path for path in allow_write if path != write_path]
    atomic_write(path, json.dumps(settings, indent=2, ensure_ascii=False) + "\n")
    os.unlink(state_path)
    print(f"removed Claude rules -> {path}")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--agent", choices=("auto", "codex", "claude", "all"), default="auto")
    action = ap.add_mutually_exclusive_group()
    action.add_argument("--install", action="store_true", help="write the proposed permission configuration")
    action.add_argument("--remove", action="store_true", help="remove entries previously installed by this script")
    ap.add_argument("--yes", action="store_true", help="confirm installation/removal non-interactively")
    ap.add_argument("--force", action="store_true", help="replace an unmanaged tool-audit.rules file")
    args = ap.parse_args()
    if args.yes and not (args.install or args.remove):
        ap.error("--yes requires --install or --remove")
    agents = selected_agents(args.agent)
    if not args.remove:
        preview(agents)
    else:
        print("tool-audit permission removal proposal:")
        for agent in agents:
            print(f"  {agent}: remove only entries recorded by tool-audit setup")
    if not (args.install or args.remove):
        print("\nDry run only. Re-run with --install after reviewing the proposal.")
        return
    if not args.yes:
        if not sys.stdin.isatty():
            raise RuntimeError("interactive confirmation unavailable; re-run with --yes after user approval")
        verb = "Remove" if args.remove else "Install"
        if input(f"\n{verb} this proposal? [y/N] ").strip().lower() not in ("y", "yes"):
            print("cancelled")
            return
    for agent in agents:
        if agent == "codex" and args.remove:
            remove_codex()
        elif agent == "claude" and args.remove:
            remove_claude()
        elif agent == "codex":
            install_codex(args.force)
        else:
            install_claude()
    if "codex" in agents:
        print("Restart Codex so the new rules are loaded.")


if __name__ == "__main__":
    sys.exit(main())
